# Generated by Django 5.0.3 on 2024-04-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='genericuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
