# Generated by Django 5.0.3 on 2024-05-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0003_department_staff_attendant_visitor_visitorlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentName',
            field=models.CharField(choices=[("MD's OFFICE", "md's Office"), ('HR', 'human resource'), ('ADMIN', 'admin'), ('NOC', 'noc'), ('SCC', 'scc'), ('MARKETING', 'marketing'), ('FACILITY', 'facility'), ('INNOVATION', 'innovation'), ('DTH', 'dth'), ('ISSD', 'issd')], default='MARKETING', max_length=50, unique=True),
        ),
    ]
