# Generated by Django 5.0.3 on 2024-05-16 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0004_alter_department_departmentname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='regDate',
            new_name='registrationDate',
        ),
        migrations.AddField(
            model_name='visitor',
            name='checkOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='registrationTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
