# Generated by Django 5.0.3 on 2024-06-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0005_rename_regdate_visitor_registrationdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='dateTime',
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='checkInTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='checkOutTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
