# Generated by Django 5.0.3 on 2024-06-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0006_remove_visitor_datetime_alter_visitorlog_checkintime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staffId',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
