# Generated by Django 5.0.3 on 2024-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0008_alter_staff_staffid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendant',
            name='staff',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='organization',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
