# Generated by Django 5.0.3 on 2024-07-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0010_remove_visitor_whomtosee_visitor_whomtosee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitrequest',
            name='attendant',
        ),
    ]
