# Generated by Django 5.0.3 on 2024-07-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0011_remove_visitrequest_attendant'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='origin',
            field=models.CharField(choices=[('onsite', 'onsite'), ('online', 'online')], default='online', max_length=8),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
