# Generated by Django 5.0.3 on 2024-07-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0012_visitor_origin_visitor_visitdate_visitor_visittime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Dismissed', 'Dismissed')], default='Pending', max_length=16),
        ),
    ]
