# Generated by Django 5.0.3 on 2024-07-30 13:23

import vms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0014_alter_visitorlog_attendant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='registrationDate',
            field=models.DateField(default=vms.models.Visitor.get_current_date),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='registrationTime',
            field=models.TimeField(default=vms.models.Visitor.get_current_time),
        ),
    ]
