# Generated by Django 5.0.3 on 2024-07-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0015_alter_visitor_registrationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentName',
            field=models.CharField(choices=[('MD OFFICE', 'md Office'), ('HR', 'human resource'), ('ADMIN', 'admin'), ('NOC', 'noc'), ('SCC', 'scc'), ('MARKETING', 'marketing'), ('FACILITY', 'facility'), ('INNOVATION', 'innovation'), ('DTH', 'dth'), ('ISSD', 'issd')], default='MARKETING', max_length=50, unique=True),
        ),
    ]
