# Generated by Django 5.0.3 on 2024-07-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0016_alter_department_departmentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentName',
            field=models.CharField(choices=[('MD', 'md'), ('HR', 'human resource'), ('ADMIN', 'admin'), ('NOC', 'noc'), ('SCC', 'scc'), ('MARKETING', 'marketing'), ('FACILITY', 'facility'), ('INNOVATION', 'innovation'), ('DTH', 'dth'), ('ISSD', 'issd')], default='MARKETING', max_length=50, unique=True),
        ),
    ]
